
# Intra-cluster SSH: map tpu0-tpu3 to internal IPs and use cluster key
Host tpu0
    HostName 10.130.0.12
Host tpu1
    HostName 10.130.0.11
Host tpu2
    HostName 10.130.0.10
Host tpu3
    HostName 10.130.0.13

Host tpu0 tpu1 tpu2 tpu3
    IdentityFile ~/.ssh/cluster
